[package]
name = "simple_bump"
description = " A collection of simple, pure Rust memory allocators."
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/rysndavjd/simple_alloc"
repository = "https://github.com/rysndavjd/simple_alloc"

[dependencies]

[features]
default = ["bump_alloc", "allocator-api"]
std = []
allocator-api = []
bump_alloc = []
